### ISSUE TITLE
两个疑惑之处

### ISSUE THREAD

**Issue by 1140325971** [hwwang55/DKN#12]
在数据处理过程中，若设置浏览历史数目为30的话，最终得到一个数据结构，每行的格式是
用户id    用户浏览历史标题（一个30×10的二维数组）用户浏览历史实体（一个30×10的二维数组）   新闻标题    新闻实体    Label
有以下几个疑惑：
1.若某一个用户的记录不足30条，代码中似乎使用重复新闻来填充这个30，这样在训练过程中会不会增加误差呢？
2.实验的训练环节采用了将整个训练集分为很多batch，我发现在attention中，会将clicked_words的维度改变为（batch_size*max_click_history,max_title_length），这样做是不是错把一个用户的浏览历史给换成一个batch中的用户的浏览历史了呢？
@hwwang55

**Comment by iDimple** [comment]
1.若某一个用户的记录不足30条，代码中似乎使用重复新闻来填充这个30，这样在训练过程中会不会增加误差呢？
这个应该属于冷启动问题，我也有这个疑问，对于用户历史记录不足的应该使用下面哪种方法呢：
1.直接删除这些记录，只使用历史记录足够的
2.像这里重复填充过去的记录
如果选2，如果是推荐top10，但是分配到测试集里的数据没有10条的应该怎么办，推荐重复的么

**Comment by hwwang55** [comment]
您好，感谢您对我们工作的兴趣！填充的目的是想保持minibatch内每个用户的记录数一致，这样对于tensorflow的计算会更高效一点。直接删除当然也是可以的，不过这样会丢失一些用户的数据。top10的推荐当然是可以的，只要整个item set的大小大于10就可以，这和用户在test set里是否有10条记录无关。

**Comment by iDimple** [comment]
谢谢老师，可是如果用户历史记录没有10条，假设只有5条，给用户推荐top10，必然会错5条，那么这个准确率肯定不会高呀
