### ISSUE TITLE
关于TransE代码的一些疑问

### ISSUE THREAD

**Issue by songzeceng** [hwwang55/DKN#13]
你好，TransE代码有一部分实在看不明白，故求教一下
https://user-images.githubusercontent.com/35772225/68124864-49f60200-ff4b-11e9-9a72-a79d77ca5cc6.png
上图中这部分初始化的四个数组rigTail、lefTail、rigHead和lefHead..到底是干什么用的?我在纸上做了下演草，还是看不出所以然..还望王博抽空解疑一下，谢谢

**Comment by hwwang55** [comment]
你好，这部分代码不是我写的，如果有问题，可以去https://github.com/thunlp/Fast-TransX提问。非常感谢！
