### ISSUE TITLE
About the kg.txt

### ISSUE THREAD

**Issue by Cindy-xdZhang** [hwwang55/DKN#15]
Thanks for providing the code.
I have two questions:
1.where is the source of the knowledge graph(kg.txt)? is it like the paper said extract from the bing server?
2. I 've checked other issues and I am wondering whether this is the full version of the dataset?
If it's because of the privacy policy, I totally understand, I just want to make sure a little bit.

Finally, thanks again~
@hwwang55

**Comment by hwwang55** [comment]
Hi! Thanks for your interest in our work. The kg.txt is extracted from the internal KG of Microsoft. This is not the full version of the dataset due to the privacy policy, as you mentioned. Thanks.
