### ISSUE TITLE
Question about DKN/data/kg/kg_preprocess.py /

### ISSUE THREAD

**Issue by iDimple** [hwwang55/DKN#17]
def get_neighbors_for_entity(file):
    reader = open(file, encoding='utf-8')
    entity2neighbor_map = {}
    for line in reader:
        array = line.strip().split('\t')
        if len(array) != 3:  # to skip the first line in triple2id.txt
            continue
        head = int(array[0])
        tail = int(array[1])
DKN/data/kg/kg_preprocess.py  should the line 30 be"tail = int(array[2])"?

**Comment by hwwang55** [comment]
Hi! Each line in triple2id.txt is with format "head, tail, relation". Thanks.
