### ISSUE TITLE
Question about the experimental results

### ISSUE THREAD

**Issue by iDimple** [hwwang55/DKN#18]
.

**Comment by iDimple** [comment]
Although the sample dataset is different from the original dataset, the result in epoch 1 was 0.5389 and the result in epoch 9 is 0.5573. DKN only improved 0.02.  And it is a prediction of 0/1, if random select the result, the expecation is 0.55. Did it mean the effect of the DKN was not very good?

**Comment by iDimple** [comment]
what is the threshold for f1 after sigmoid? I set it 0.5 and the f1 was 0.71 which was much larger than the 0.68 in paper

**Comment by luoyujiaye** [comment]
I also have some confusion, I see all the probability of model is larger than 0.5

**Comment by Kevin9780** [comment]
> I also have some confusion, I see all the probability of model is larger than 0.5

我也发现了同样的问题，请问您找到原因了吗？

**Comment by luoyujiaye** [comment]
> > I also have some confusion, I see all the probability of model is larger than 0.5
> 
> 我也发现了同样的问题，请问您找到原因了吗？
模型的网络层中Relu位于所有的可训练参数之上, 我觉得应该是这个原因导致的

**Comment by Wei-Qi** [comment]
大家训练了多长时间哎
