### ISSUE TITLE
请问在训练的时候怎么样在训练集里划分出用户的history clicked news 

### ISSUE THREAD

**Issue by iDimple** [hwwang55/DKN#20]
王老师好，代码中，在训练的时候，是把训练集中的30条划分成history clicked news ，请问为什么这么分，是实验做出来的超参数么
1.为什么不在训练的时候除了其中一条作为候选集其他的都当成历史记录，然后重复这个过程直到训练集中的所有数据都当过候选集呢
2.训练的时候是将用户所有标签为1的记录当成他的历史记录，还是标签为0的也会当成历史记录
3.候选集是怎么生成的？
4.有没有比较过不同条数的历史记录对模型的影响
5.测试集使用的历史记录和训练集一样么，还是使用用户的训练集作为测试时的历史记录
谢谢老师

**Comment by iDimple** [comment]
请问是训练的时候只训练一部分用户，测试的时候测试另一部分用户，而不是将所有用户的一部分放在训练集，一部分放在测试集么

**Comment by hwwang55** [comment]
你好，30条只是一个设定，这个是可以调整的。
1. 当然可以，这就是leave-one-out的方式；
2. 标签为0的也会被当成历史记录；
3. 候选集包含了所有的item；
4. 一般而言历史记录越多，效果会越好，不过会有边际效应递减的现象；
5. 测试集不可以和训练集重复。
