### ISSUE TITLE
c++程序无法执行

### ISSUE THREAD

**Issue by wjy3326** [hwwang55/DKN#26]
想问下执行这步操作g++ transE.cpp -o transE -pthread -O3 -march=native时没有反应，也没有报错，不知道是什么原因。首先用transE执行，没有生成结果文件，也没有报错
(image_text_match_tf_1.15) [user@tianhu-worker-5 Fast-TransX]$ cd transE
(image_text_match_tf_1.15) [user@tianhu-worker-5 transE]$ g++ transE.cpp -o transE -pthread -O3 -march=native
(image_text_match_tf_1.15) [user@tianhu-worker-5 transE]$

然后用transD，生成了一个trnaD文件，但是也没有生成TransD_relation2vec_50.vec文件，请问是什么原因呢？
(image_text_match_tf_1.15) [user@tianhu-worker-5 kg]$ cd Fast-TransX/transD/
(image_text_match_tf_1.15) [user@tianhu-worker-5 transD]$ g++ transD.cpp -o transD -pthread -O3 -march=native
(image_text_match_tf_1.15) [user@tianhu-worker-5 transD]$ ls

**Comment by suyogkute** [comment]
Did you find the cause or solution for first problem, please let me know here
