### ISSUE TITLE
the l2_loss variable needs to be claimed as non-trainable

### ISSUE THREAD

**Issue by hurenjun** [hwwang55/DKN#5]
dkn.py line 141

self.l2_loss  needs to be claimed as non-trainable, i.e.,
self.l2_loss  = tf.Variable(tf.constant(0., dtype=tf.float32), trainable=False)

In the current version, the l2_loss gets negative results since it is also trained. But I found that other model parameters are updated correctly.

**Comment by hwwang55** [comment]
Bug fixed. Thanks!
